services:
  jenkins:
      container_name: jenkins
      image: jenkins/jenkins:lts
      privileged: true
      ports:
        - "5080:8080"
        - "50000:50000"
      volumes:
        - jenkins_home:/var/jenkins_home
      environment:
        - JAVA_OPTS=-Djenkins.install.runSetupWizard=true
        - TZ=America/Bogota
      networks:
        - devops

  slave:
      image: jenkins/agent:latest
      container_name: slave
      init: true
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
        - slave_home:/home/jenkins/agent
      command: >
        java -jar /usr/share/jenkins/agent.jar -workDir /home/jenkins/agent -url http://jenkins:8080 -name slave -webSocket -workDir "/home/jenkins/agent" -secret 9019ea2ca2a2c4588dbdda70a5a05836792033bfdc35cbae8d674bd7dd689b7f
      networks:
        - devops



volumes:
  jenkins_home:
  slave_home:

networks:
  devops:
   external: true
