apiVersion: v1
kind: Service
metadata:
  name: ms-agosto-01-java
  namespace: devops
  labels:
    app: ms-agosto-01-java
spec:
  type: LoadBalancer
  selector:
    app: ms-agosto-01-java
  ports:
    - name: http
      port: 9090
      targetPort: 8888
