services:
  ms-agosto-01-java:
    container_name: ms-agosto-01-java
    image: mauron/ms-agosto-01:TAG
    ports:
      - "9090:8888"
    environment:
      - MESSAGE="hola k8s"
      - TZ=Americas/Bogota
    restart: unless-stopped

