
name: Java CI with Maven

on:
  push:
    branches: [ "main", "dev", "feature/*" ]
  pull_request:
    branches: [ "main" ]


jobs:
  ci:

    uses: gmacastil/pipelines/.github/workflows/ci-java.yml@main

